/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ButtonColumn;
import controlador.Controlador;
import java.awt.Color;
import java.awt.event.ItemListener;
import javax.swing.event.DocumentListener;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author benja
 */
public class vistaHome extends javax.swing.JFrame implements InterfazTurno {

    private final DefaultTableModel modeloTblTurnos;
    
    
    private ButtonColumn columnaBoton;
    
    public ButtonColumn getColumnaBoton() {
        return columnaBoton;
    }

    public void setColumnaBoton(ButtonColumn columnaBoton, Controlador c) {
        this.columnaBoton = columnaBoton;
        this.columnaBoton.setControlador(c);
    }
    
    public DefaultTableModel getModeloTblTurnos() {
        return modeloTblTurnos;
    }
    
    public JTable getTablaTurnos() {
        return TablaTurnos;
    }
    
    /**
     * Creates new form vistaHome
     */
    public vistaHome() {
        initComponents();
        this.modeloTblTurnos = (DefaultTableModel) this.TablaTurnos.getModel();
        this.setTitle("VISTA HOME");
        this.NuevoTurnoBtn.setName("BotonNuevoTurno");
        DefaultTableCellRenderer centerRenderer = (DefaultTableCellRenderer)this.TablaTurnos.getDefaultRenderer(Object.class);
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        this.TablaTurnos.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        this.TablaTurnos.getTableHeader().setOpaque(false);
        this.TablaTurnos.getTableHeader().setBackground(Color.GRAY);
        this.TablaTurnos.getTableHeader().setFont(new java.awt.Font("Ubuntu", 1, 14));
        this.TablaTurnos.getTableHeader().setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLabel = new javax.swing.JLabel();
        NuevoTurnoBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaTurnos = new javax.swing.JTable();
        ComboFiltro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(201, 189, 189));

        TituloLabel.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        TituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLabel.setText("SuperCharger S.R.L.");

        NuevoTurnoBtn.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        NuevoTurnoBtn.setText("Nuevo Turno");
        NuevoTurnoBtn.setActionCommand("TURNO");
        NuevoTurnoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoTurnoBtnActionPerformed(evt);
            }
        });

        TablaTurnos.setBackground(new java.awt.Color(230, 230, 230));
        TablaTurnos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(111, 111, 111)));
        TablaTurnos.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        TablaTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro", "Ano_Mes", "Dia", "Hora", "Mecanico", "Vehiculo", "Titular", "Compania", "Estado", "FichaMecanica"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaTurnos.setToolTipText("");
        TablaTurnos.setAlignmentX(1.0F);
        TablaTurnos.setAlignmentY(1.0F);
        jScrollPane1.setViewportView(TablaTurnos);

        ComboFiltro.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        ComboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asignado", "No Asignado", "Confirmado", "Finalizado", "Cancelado", "Todos" }));
        ComboFiltro.setActionCommand("FILTRAR_TABLA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1206, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NuevoTurnoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(TituloLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevoTurnoBtn)
                    .addComponent(ComboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoTurnoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoTurnoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoTurnoBtnActionPerformed

    public JComboBox<String> getComboFiltro() {
        return ComboFiltro;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboFiltro;
    private javax.swing.JButton NuevoTurnoBtn;
    private javax.swing.JTable TablaTurnos;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(Controlador c, ItemListener ci, DocumentListener li) {
        this.NuevoTurnoBtn.addActionListener(c);
        this.ComboFiltro.addActionListener(c);
    }

    @Override
    public void iniciaVista() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    @Override
    public void cerrarVista() {
        setVisible(false);
    }

    @Override
    public void limpiaVista() {
        this.TablaTurnos.clearSelection();
    }
}
