@startuml
package Modelo <<Folder>>{
    class Modelo{
    }
    abstract Persona extends Modelo{    
        nombre: String
        edad: String
        apellio: String
        tipoDNI: String
        nroDNI: String
        telefono: Telefono
        direccion: String
        email: String
    }
    class Turno extends Modelo{
        nro: Int
        dia: Date
        hora: Date
        mecanico: Mecanico
        vehiculo: Vehiculo
        titular: Titular
        companiaSeguro: CompaniaSeguro
        estado: Estado
        fichaMecanica: FichaMecanica
    }
    class CompaniaSeguro{
        razonSocial: String
        cuit: String
        direccion: Direccion
        telefono: Telefono
        listadoTitulares: List<Titular>
    }

    class Vehiculo{
        nroPoliza: Int
        modelo: String
        marca: String
    }
    
    class Cliente extends Persona{
        vehiculo: Vehiculo
        companiaSeguro: CompaniaSeguro
    }

    class Empleado extends Persona{
        legajo: String
        area: Area
    }

    class Area{
        codigo: String
        nombre: String
        descripcion: String
    }

    class Mecanico{
        
    }

    class Agenda{
        mes: Date
        listadoTurnos: List<Turno>
        mecanico: Mecanico
    }

    class ManoObra{
        codigo: String
        nombre: String
        descripcion: String
        precio: Float
    }

    class Material{
        codigo: String
        nombre: String
        descripcion: String
        precio: Float
        tipo: tipoMaterial 
    }

    class TipoMaterial{
        nombre: String
        descripcion: String
    }   

    class DetalleFichaMecanica{
        nuromeroDetalle: Int
        material: Materla
        manoObra: ManoObra
        cantidad: Float
        subtotal: Float
    }

    class Mecanico{
        horarioAtencionInicio: Date
        horarioAtencionFin: Date
        especialidad: List<Especialidad>
        cantidadTurnosPorDia: Int
    }

    class Especialidad{
        codigo: String
        nombre: String
        descripcion: String
    }

    interface Estado{
        + procesar()
    }

    class Asignado{
        + procesar()
    }

    class NoAsignado{
        + procesar()
    }

    class Cancelado{
        + procesar()
    }

    class Finalizado{
        + procesar()
    }

    class EnCurso{
        + procesar()
    }

    class FabricaPersona extends FabricaPersonaMethods{
    }
    
    class FabricaPersonaMethods{
    }
}

package Controlador <<Folder>>{
    class EncRecepcionControlador{
        listadoAgendas: List<Agenda>
        + registrarTurno(Turno)
        + cancelarTurno(Turno)
        + consultarTurno(Turno)
        + registrarAsistencia(Turno)
        + generarAgenda(Mecanico)
        + generarFichaMecanica(Turno)
        + generarComprobanteReserva(Turno)
        + generarInformePorMecanico(Mecanico)
        + registrarCliente(Titular)
    }

    class EncTallerControlador{
        listadoFichasMecanicas: List<FichaMecanica>
        + generarConstaciaConformidad()
        + registrarConstanciaConformidad()
        + registrarFichaMecanica()
    }

    class EnsAdministracionControlador{
        listadoCompanias: List<CompaniaSeguro>
        listadoAgendas: List<Agenda>
        +registrarCobroCompania()
        +generarInformeCompania(Compania)
    }

    abstract FabricaControladorPersona{
    }

    class FabricaControlador extends FabricaControladorPersona{
    }
}

package Vista <<Folder>>{
    interface FichaMecanica{
        numeroFicha: Int
        titular: Titular
        mecanico: Mecanico
        listaDetalle: List<DetalleFichaMecanica>
        total: Float
    }

    interface VistaTurno{
        
    }

    interface Home{
        
    }
}

 package DAO <<Folder>>{
    abstract FabricaDAO{
        + abstract AlumnoDAOgetAlumnoDao()
        + abstract TurnoDAO getTurnoDao()
        + static FabricaDAO getFactory(String nombreClase)
    }

    interface TurnoDAO{
        + TurnoDTO consultarTurno(String nro)
        + List<TurnoDTO> listarTurnos()
        + boolean insertarTurno(String nro, String dia, String hora, String mecanico,
                                String vehiculo, String titular, 
                                String companiaSeguro)
        + boolean modificarTurno(String nro, String dia, String hora, String mecanico)
        + boolean confirmarTurno(String nro)
        + boolean cancelarTurno(String nro)
        + boolean registrarFichaMecanica(String nro, String fichaMecanica)
        + void cerrarConexion()
    }

    class TurnoDAOImpSQL extends TurnoDAO{
        
    }

    class SQLFabricaDAO extends FabricaDAO{
        + @Override AlumnoDAO getAlumnoDao()
        + @Override TurnoDAO getTurnoDao()
    }

    package Singleton <<Folder>>{
        class ConexionSQL{
            - static final String URL
            - Connection connection
            - static ConexionSql instancia
            - ConexionSql()
            + static ConexionSql getInstancia()
            + Connection getConnection()
            # void desconectar()
        }
    }
 }

    Turno --> Vehiculo
    Turno --> CompaniaSeguro
    Turno *--> Estado
    Turno "0-n" --> "1" Mecanico
    Turno "0-n" --> "1" Vehiculo
    Turno "0-1" <--* "1" Agenda
    Turno "1" <-- "1"  FichaMecanica
    Asignado --|> Estado
    NoAsignado --|> Estado
    Cancelado --|> Estado 
    EnCurso --|> Estado
    Finalizado --|> Estado
    Cliente --> Vehiculo
    Cliente --> CompaniaSeguro
    Empleado "0-n" --> "1" Area
    FabricaPersona "<instancia>" ..>  Cliente
    FabricaPersona "<instancia>" ..> Empleado
    Mecanico "0-n" --> "1-n" Especialidad
    Especialidad "1" --> "1-n" ManoObra
    FabricaControlador "<instancia>" ..> EnsAdministracionControlador
    FabricaControlador "<instancia>" ..> EncTallerControlador
    FabricaControlador "<instancia>" ..> EncRecepcionControlador
    EncRecepcionControlador --> Turno
    EncRecepcionControlador --> VistaTurno
    EncRecepcionControlador --> ConexionSQL
    EncRecepcionControlador  "1" --> "1-n" Agenda
    FichaMecanica "0-n" --> "1" Mecanico
    EncTallerControlador "1" --> "0-n" FichaMecanica
    CompaniaSeguro "1-n" --> "1" EnsAdministracionControlador
    FichaMecanica "1" *--> "1-n" DetalleFichaMecanica
    DetalleFichaMecanica "0-n" --> "0-1" Material
    DetalleFichaMecanica "0-n" --> "0-1" ManoObra
    Material "1-n" --> "1" TipoMaterial
   
@enduml
